#pragma once

#define WELL_KNOWN_ATOMS(X)                                                    \
  X(atom_true, "true")                                                         \
  X(atom_comma, ",")                                                           \
  X(atom_dot, ".")                                                             \
  X(atom_nil, "[]")                                                            \
  X(atom_ruleop, ":-")                                                         \
  X(atom_slash, "/")                                                           \
  X(atom_error, "error")                                                       \
  X(atom_instantiation_error, "instantiation_error")                           \
  X(atom_type_error, "type_error")                                             \
  X(atom_existence_error, "existence_error")                                   \
  X(atom_evaluation_error, "evaluation_error")                                 \
  X(atom_zero_divisor, "zero_divisor")                                         \
  X(atom_int_overflow, "int_overflow")                                         \
  X(atom_stream, "$stream")                                                    \
  X(atom_uncatch, "$$uncatch")                                                 \
  X(atom_cut, "$$cut")                                                         \
  X(atom_bang, "!")                                                            \
  X(atom_dyn_call, "$dyn_call")                                                \
  X(atom_catch, "catch")                                                       \
  X(atom_throw, "throw")                                                       \
  X(atom_assertz, "$$assertz")                                                 \
  X(atom_assert, "$$assert")                                                   \
  X(atom_asserta, "$$asserta")                                                 \
  X(atom_retract, "$$retract")                                                 \
  X(atom_call, "call")                                                         \
  X(atom_plus, "+")                                                            \
  X(atom_minus, "-")                                                           \
  X(atom_star, "*")                                                            \
  X(atom_intdiv, "//")                                                         \
  X(atom_mod, "mod")                                                           \
  X(atom_min, "min")                                                           \
  X(atom_max, "max")                                                           \
  X(atom_abs, "abs")                                                           \
  X(atom_sign, "sign")                                                         \
  X(atom_floor, "floor")                                                       \
  X(atom_ceiling, "ceiling")                                                   \
  X(atom_round, "round")                                                       \
  X(atom_truncate, "truncate")                                                 \
  X(atom_op_pred, "$$op")                                                      \
  X(atom_optype_xfx, "xfx")                                                    \
  X(atom_optype_xfy, "xfy")                                                    \
  X(atom_optype_yfx, "yfx")                                                    \
  X(atom_optype_fx, "fx")                                                      \
  X(atom_optype_fy, "fy")                                                      \
  X(atom_is, "is")                                                             \
  X(atom_unify_op, "=")                                                        \
  X(atom_unify_oc, "unify_with_occurs_check")                                  \
  X(atom_lt, "<")                                                              \
  X(atom_gt, ">")                                                              \
  X(atom_put_code, "put_code")                                                 \
  X(atom_get_code, "get_code")                                                 \
  X(atom_write_raw, "$$write_raw")                                             \
  X(atom_open, "open")                                                         \
  X(atom_close, "close")                                                       \
  X(atom_consult, "$$consult")                                                 \
  X(atom_dynamic, "dynamic")                                                   \
  X(atom_capture_start, "$$capture_start")                                     \
  X(atom_capture_stop, "$$capture_stop")                                       \
  X(atom_fail, "fail")                                                         \
  X(atom_false, "false")                                                       \
  X(atom_halt, "halt")                                                         \
  X(atom_flush_output, "flush_output")                                         \
  X(atom_read_line_to_atom, "read_line_to_atom")                               \
  X(atom_end_of_file, "end_of_file")                                           \
  X(atom_user_input, "user_input")                                             \
  X(atom_unload, "$$unload")                                                   \
  X(atom_is_static_pred, "$$is_static")                                        \
  X(atom_undynamic, "$$undynamic")                                             \
  X(atom_prolog_flags, "$$prolog_flags")                                       \
  X(atom_flag_bounded, "bounded")                                              \
  X(atom_flag_max_integer, "max_integer")                                      \
  X(atom_flag_min_integer, "min_integer")                                      \
  X(atom_flag_integer_rounding_function, "integer_rounding_function")          \
  X(atom_flag_max_arity, "max_arity")                                          \
  X(atom_flag_double_quotes, "double_quotes")                                  \
  X(atom_toward_zero, "toward_zero")                                           \
  X(atom_chars_kw, "chars")                                                    \
  X(atom_bitand, "/\\")                                                        \
  X(atom_bitor, "\\/")                                                         \
  X(atom_bitxor, "xor")                                                        \
  X(atom_shl, "<<")                                                            \
  X(atom_shr, ">>")                                                            \
  X(atom_bitnot, "\\")                                                         \
  X(atom_var, "var")                                                           \
  X(atom_kw_atom, "atom")                                                      \
  X(atom_integer, "integer")                                                   \
  X(atom_kw_float, "float")                                                    \
  X(atom_compound, "compound")                                                 \
  X(atom_functor, "functor")                                                   \
  X(atom_arg, "arg")                                                           \
  X(atom_univ, "=..")                                                          \
  X(atom_atom_codes, "atom_codes")                                             \
  X(atom_number_codes, "number_codes")                                         \
  X(atom_mode_read, "read")                                                    \
  X(atom_mode_write, "write")                                                  \
  X(atom_mode_append, "append")                                                \
  X(atom_copy_term, "copy_term")                                               \
  X(atom_term_to_atom, "term_to_atom")                                         \
  X(atom_atom_to_term, "atom_to_term")                                         \
  X(atom_clause_candidates, "$$clause_candidates")                             \
  X(atom_choice_mark, "$$choice_mark")                                         \
  X(atom_cut_to, "$$cut_to")                                                   \
  X(atom_arith_le, "=<")                                                       \
  X(atom_arith_ge, ">=")                                                       \
  X(atom_arith_eq, "=:=")                                                      \
  X(atom_arith_ne, "=\\=")                                                     \
  X(atom_term_eq, "==")                                                        \
  X(atom_term_ne, "\\==")                                                      \
  X(atom_term_lt, "@<")                                                        \
  X(atom_term_gt, "@>")                                                        \
  X(atom_term_le, "@=<")                                                       \
  X(atom_term_ge, "@>=")                                                       \
  X(atom_semicolon, ";")                                                       \
  X(atom_arrow, "->")                                                          \
  X(atom_qmark_dash, "?-")

enum {
#define X(name, text) name,
  WELL_KNOWN_ATOMS(X)
#undef X
      WELL_KNOWN_ATOM_COUNT
};
