#!/bin/sh
set -eu

echo '// Generated by tools/embed_libs.sh; do not edit.'
echo '#include "embedded.h"'
echo

i=0
for f in "$@"; do
  printf 'static const unsigned char file%d[] = {\n' "$i"
  # Whole-line comments only: a % mid-line may be inside quotes or a 0'%.
  grep -v -E '^[[:space:]]*(%.*)?$' "$f" | od -An -v -tx1 | sed -e 's/[0-9a-f][0-9a-f]/0x&,/g'
  printf '    0x00};\n\n'
  i=$((i + 1))
done

echo 'const embedded_file embedded_files[] = {'
i=0
for f in "$@"; do
  printf '    {"%s", (const char *)file%d, sizeof file%d - 1},\n' "$f" "$i" "$i"
  i=$((i + 1))
done
echo '    {0, 0, 0}};'
